### ISSUE TITLE
Deck tracker does not connect when starting a new game.

### ISSUE THREAD

**Issue by wdprez** [Sebski123/YARDT#4]
When I start the deck tracker while I am playing a game, there are no issues, but then on the next game, the tracker does not connect. It registers that a game has started (seen by auto minimize/maximize), but no images are shown in the deck bar. When I change the port to something else and then change the port back to the original number, the problem is solved. But now I need to do this workaround every game, so this is not really enjoyable. Any idea what could be the issue?

**Comment by Nightfly13** [comment]
We are aware of the issue but unfortunately it is not possible for us to fix it. It is actually due to Riot's API not being complete it seems. If you go to your web browser and go to http://localhost:PORT/static-decklist (replace PORT with the port that you are using) while you are in game, it will show you a list of the card codes and the amount of cards that you have in your deck. This is the main thing that we use for the deck tracker to generate all of the card tiles. However, for no apparent reason, it will just sometimes not load. It is different from machine to machine as well- for some people, changing the port once fixes it, for others such as yourself, it continues to bug out no matter what. The reason why the auto minimize works is because we also use a different part of the API (http://localhost:PORT/positional-rectangles) for things such as the cards in hand that functions seemingly every time with no issues. Hopefully Riot can fix these issues, because as it is right now, there is no way for us to avoid them.
